services:
    react-app-dockerize:
        # Set the container name
        container_name: surprise4mefrontend

        # set name for the image
        image: surprise4meimage

        # Build the image using the Dockerfile in the current context
        build:
            context: .
            dockerfile: Dockerfile
  
        ports:
            - "3000:3000" #<host_port>:<container_port/protocol_port>

        # Mount the current directory to /app in the container
        volumes:
            - .:/app
            - /app/node_modules

        # Specify the command to run when the container starts
        command: npm run dev